apiVersion: 1

contactPoints:
  - orgId: 1
    name: Slack NetWatch
    receivers:
      - uid: slack-netwatch
        type: slack
        settings:
          url: ${SLACK_WEBHOOK_URL}
          username: NetWatch Alerting
          icon_emoji: ":shield:"
          title: "[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}"
          text: |
            *Severité :* {{ range .Alerts }}{{ .Labels.severity }}{{ end }}
            *Description :* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
            *Valeur :* {{ range .Alerts }}{{ .Annotations.value }}{{ end }}
        disableResolveMessage: false

  - orgId: 1
    name: AutoBlock
    receivers:
      - uid: autoblock-webhook
        type: webhook
        settings:
          url: http://netwatch-autoblock:5001/webhook/alert
          httpMethod: POST
        disableResolveMessage: true
