apiVersion: 1

datasources:
  - name: Zeek-ES
    type: elasticsearch
    uid: zeek-es
    access: proxy
    url: http://elasticsearch:9200
    database: "zeek-*"
    isDefault: true
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
      logMessageField: message
      logLevelField: fields.level
    editable: true

  - name: Snort-ES
    type: elasticsearch
    uid: snort-es
    access: proxy
    url: http://elasticsearch:9200
    database: "snort-*"
    isDefault: false
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
    editable: true

  - name: Suricata-ES
    type: elasticsearch
    uid: suricata-es
    access: proxy
    url: http://elasticsearch:9200
    database: "suricata-*"
    isDefault: false
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
    editable: true
