apiVersion: 1

datasources:
  - name: Zeek-ES
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "zeek-*"
    isDefault: true
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
      logMessageField: message
      logLevelField: fields.level
    editable: true
